name: "Chromatic publish"

on:
  push:
    branches:
      - main

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nécessaire pour récupérer l'historique git complet

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Utilisez la version de Node adaptée à votre projet

      - name: Install dependencies
        run: npm ci # ou yarn install --frozen-lockfile si vous utilisez Yarn

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # Options supplémentaires si nécessaire
          autoAcceptChanges: true
          exitZeroOnChanges: true
