name: 🚀 Build and publish Chromatic

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: 🎉 Deploy
    strategy:
      fail-fast: false
      matrix:
        operating-system: [windows-latest]
        node-versions: ["22"]

    # The type of runner that the job will run on
    runs-on: ${{ matrix.operating-system }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-outs your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Récupère tout l'historique pour permettre à Chromatic de comparer les commits

      - name: 🔨 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versions }}

      - name: 🔨 Install dependencies
        run: npm i --no-package-lock

      - name: 📂 Deploy stage
        id: deployStage
        run: |
          npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
