name: "Chromatic publish"

on:
  push:
    branches:
      - main # Assurez-vous que cette branche correspond à votre branche principale

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nécessaire pour récupérer l'historique git complet

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Vérifiez que cette version correspond à votre projet

      - name: Install dependencies
        run: npm ci # Remplacez par 'yarn install --frozen-lockfile' si vous utilisez Yarn

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true # Accepte automatiquement les changements visuels
          exitZeroOnChanges: true # Ne fait pas échouer le workflow si des changements sont détectés
